### ISSUE TITLE
Demo!

### ISSUE THREAD

**Issue by NPrescott** [keith/vote-knope#1]
Nice idea. Obviously I want to demo this, I imagine I'm not the only one.

**Comment by NPrescott** [comment]
:+1:

**Comment by keith** [comment]
Great idea, I'll get it setup on this repo soon!

**Comment by keith** [comment]
:+1:

**Comment by keith** [comment]
:+1:

**Comment by keith** [comment]
Alright, it's all setup!

**Comment by rsmoz** [comment]
﹢1

**Comment by faun** [comment]
:+1:

**Comment by faun** [comment]
Great idea!

**Comment by faun** [comment]
:-1:

**Comment by faun** [comment]
:trollface:

**Comment by rsmoz** [comment]
+1

**Comment by rsmoz** [comment]
:﹢1:

**Comment by rsmoz** [comment]
![screenshot 2016-02-05 19 38 58](https://cloud.githubusercontent.com/assets/1538471/12863110/28a217e8-cc40-11e5-97d7-09c1a64abe3d.png)

**Comment by rsmoz** [comment]
Hmm, it's not working for me...

**Comment by keith** [comment]
Many of your comments have been deleted. You'll have to refresh to see the change.

**Comment by rsmoz** [comment]
I still see them there...

**Comment by keith** [comment]
![screen shot 2016-02-05 at 16 41 05](https://cloud.githubusercontent.com/assets/283886/12863129/4389eed2-cc27-11e5-8128-26a4d247249f.png)

**Comment by mwhuss** [comment]
![w5-hpoti_400x400](https://cloud.githubusercontent.com/assets/3904/12863132/56e374ee-cc27-11e5-9383-164a5413dad2.png)

**Comment by rsmoz** [comment]
﹢1

**Comment by rsmoz** [comment]
Does anyone else see that `﹢1` or is it just me?

**Comment by keith** [comment]
I see that one yes, but that is not a valid + character.

**Comment by rsmoz** [comment]
What, like the browser can't show a + character?

**Comment by rsmoz** [comment]
I'm on the latest Safari on OS X 10.11.4 beta. Maybe that's why my browser can show the +? tbh I've always thought browsers have been able to show + but i guess I'm wrong

**Comment by Reflejo** [comment]
up

**Comment by rsmoz** [comment]
How could a + sign be invalid?

**Comment by calebd** [comment]
+1️⃣

**Comment by kmmbvnr** [comment]
+2

**Comment by kmmbvnr** [comment]
+1

**Comment by timkofu** [comment]
plus-one means "my thoughts exactly", and I don't see what the problem is with someone agreeing with someone else's articulation of a problem.

**Comment by mikeatlas** [comment]
+(1-0)

**Comment by JFKingsley** [comment]
+1

**Comment by rahuljiresal** [comment]
+1

**Comment by keith** [comment]
:+1:
